services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: audit
      POSTGRES_USER: audit
      POSTGRES_PASSWORD: audit
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
