/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainEditAuditAuditIdRouteImport } from './routes/_main.edit-audit.$auditId'
import { Route as MainAuditsDatetimeRouteImport } from './routes/_main.audits.$datetime'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainEditAuditAuditIdRoute = MainEditAuditAuditIdRouteImport.update({
  id: '/edit-audit/$auditId',
  path: '/edit-audit/$auditId',
  getParentRoute: () => MainRoute,
} as any)
const MainAuditsDatetimeRoute = MainAuditsDatetimeRouteImport.update({
  id: '/audits/$datetime',
  path: '/audits/$datetime',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/audits/$datetime': typeof MainAuditsDatetimeRoute
  '/edit-audit/$auditId': typeof MainEditAuditAuditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/audits/$datetime': typeof MainAuditsDatetimeRoute
  '/edit-audit/$auditId': typeof MainEditAuditAuditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/audits/$datetime': typeof MainAuditsDatetimeRoute
  '/_main/edit-audit/$auditId': typeof MainEditAuditAuditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audits/$datetime' | '/edit-audit/$auditId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audits/$datetime' | '/edit-audit/$auditId'
  id:
    | '__root__'
    | '/_main'
    | '/_main/'
    | '/_main/audits/$datetime'
    | '/_main/edit-audit/$auditId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/edit-audit/$auditId': {
      id: '/_main/edit-audit/$auditId'
      path: '/edit-audit/$auditId'
      fullPath: '/edit-audit/$auditId'
      preLoaderRoute: typeof MainEditAuditAuditIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/audits/$datetime': {
      id: '/_main/audits/$datetime'
      path: '/audits/$datetime'
      fullPath: '/audits/$datetime'
      preLoaderRoute: typeof MainAuditsDatetimeRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainAuditsDatetimeRoute: typeof MainAuditsDatetimeRoute
  MainEditAuditAuditIdRoute: typeof MainEditAuditAuditIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainAuditsDatetimeRoute: MainAuditsDatetimeRoute,
  MainEditAuditAuditIdRoute: MainEditAuditAuditIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
