/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainUploadRouteImport } from './routes/_main.upload'
import { Route as MainAuditsIndexRouteImport } from './routes/_main.audits.index'
import { Route as MainAuditsDatetimeRouteImport } from './routes/_main.audits.$datetime'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainUploadRoute = MainUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => MainRoute,
} as any)
const MainAuditsIndexRoute = MainAuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => MainRoute,
} as any)
const MainAuditsDatetimeRoute = MainAuditsDatetimeRouteImport.update({
  id: '/audits/$datetime',
  path: '/audits/$datetime',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/upload': typeof MainUploadRoute
  '/audits/$datetime': typeof MainAuditsDatetimeRoute
  '/audits/': typeof MainAuditsIndexRoute
}
export interface FileRoutesByTo {
  '/upload': typeof MainUploadRoute
  '/': typeof MainIndexRoute
  '/audits/$datetime': typeof MainAuditsDatetimeRoute
  '/audits': typeof MainAuditsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/upload': typeof MainUploadRoute
  '/_main/': typeof MainIndexRoute
  '/_main/audits/$datetime': typeof MainAuditsDatetimeRoute
  '/_main/audits/': typeof MainAuditsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upload' | '/audits/$datetime' | '/audits/'
  fileRoutesByTo: FileRoutesByTo
  to: '/upload' | '/' | '/audits/$datetime' | '/audits'
  id:
    | '__root__'
    | '/_main'
    | '/_main/upload'
    | '/_main/'
    | '/_main/audits/$datetime'
    | '/_main/audits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/upload': {
      id: '/_main/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof MainUploadRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/audits/': {
      id: '/_main/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof MainAuditsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/audits/$datetime': {
      id: '/_main/audits/$datetime'
      path: '/audits/$datetime'
      fullPath: '/audits/$datetime'
      preLoaderRoute: typeof MainAuditsDatetimeRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainUploadRoute: typeof MainUploadRoute
  MainIndexRoute: typeof MainIndexRoute
  MainAuditsDatetimeRoute: typeof MainAuditsDatetimeRoute
  MainAuditsIndexRoute: typeof MainAuditsIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainUploadRoute: MainUploadRoute,
  MainIndexRoute: MainIndexRoute,
  MainAuditsDatetimeRoute: MainAuditsDatetimeRoute,
  MainAuditsIndexRoute: MainAuditsIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
